/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sequitursort;

import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan Curley
 */
public class sequiturSortGUI extends javax.swing.JFrame {

    private Map<String,Integer> segmentTimes; //This is the list of times in a hashmap.
    private Map<String,ruleRep> globalRules;
    /**
     * Creates new form sequiturSortGUI
     */
    public sequiturSortGUI() {
        initComponents();
        cbRules.setEnabled(false);// start by disabling the combobox.
        okButton.setEnabled(false); // and the "OK" button
        cbRules.removeAllItems(); // then clear all existing items.
        globalRules = new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        taSequitur = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taSegments = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        goButton = new javax.swing.JButton();
        cbRules = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        okButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        opWindow = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taSequitur.setColumns(20);
        taSequitur.setRows(5);
        jScrollPane1.setViewportView(taSequitur);

        jLabel1.setText("1 - Paste Sequitur output here (Rules only - please remove headers)");

        jLabel2.setText("2 - Paste Segment labels and Execution times here ");

        taSegments.setColumns(20);
        taSegments.setRows(5);
        jScrollPane2.setViewportView(taSegments);

        jLabel3.setText("3 - Press \"GO\" when finished");

        goButton.setText("GO");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        cbRules.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Once the output has been generated - more rule details are available");

        jLabel5.setText("From here.  Simply select the rule from the combobox.");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        opWindow.setColumns(20);
        opWindow.setRows(5);
        jScrollPane3.setViewportView(opWindow);

        jLabel6.setText("Output Window (CTRL+C to copy)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(cbRules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(okButton))
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(goButton))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(goButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbRules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(okButton))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This is the function called when the user presses the "GO" button.
     * @param evt 
     */
    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // Build the tempArray
        String[] tempString = taSegments.getText().split("(\\r|\\n)"); // one array entry per line.         
        segmentTimes = new HashMap<String,Integer>();
                                                                 // Each line will be "Mark,ExecTime".
        for(String s:tempString){
            String[] tempArray = s.split(",");
            if(tempArray.length>1)
                segmentTimes.put(tempArray[0], Integer.valueOf(tempArray[1]));
        }
        
        tempString = taSequitur.getText().split("[\\r\\n]");
        ArrayList<ruleRep> rules = new ArrayList<>();
        
        for(String s:tempString)
            rules.add(new ruleRep(s));        
        
        // now we have a list of rules from within the program, and a list of segments and associated times.
        boolean loopsComplete;
        for(int i=0; i<rules.size();i++){ // do this a max number of times            
            loopsComplete = true;
            for(ruleRep rR:rules){
                if(!rR.checkKnownSegments(segmentTimes)){
                    JOptionPane.showMessageDialog(null,"Error - Unknown Segment", "Error", JOptionPane.ERROR_MESSAGE);
                    //System.exit(0);
                    break;
                }
                segmentTimes = rR.sortRuleRep(segmentTimes);                                                    
                if(!rR.isComplete()) // if any of the loops are incomplete - 
                    loopsComplete = false; // mark as such.
            }
            if(loopsComplete) // if loopsComplete is still TRUE - all loops have been addressed.
                i = rules.size(); // update i to exit the loop                
        }        
        // At this stage, print off each rule and it's associated execution time.
        printLine("Name,Execution Time,Complete?");        
        for(ruleRep rR:rules){
            globalRules.put(rR.getName(), rR); // build the map for further iterations.
            printLine(rR.getRuleSortDetails());
            if(rR.isComplete())
                cbRules.addItem(new String(rR.getName()));
        }
        
        cbRules.setEnabled(0<cbRules.getItemCount()); // as long as there are items, enable the CB
        okButton.setEnabled(cbRules.isEnabled()); // and the "OK" Button.
    }//GEN-LAST:event_goButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String selectedRule = (String)cbRules.getSelectedItem();
        printLine("\n-------- Rule "+selectedRule+" Selected. --------");
        ruleRep primaryRule = globalRules.get(selectedRule);

        for(String s:(ArrayList<String>)getRules(primaryRule.getName(),primaryRule))
            printLine(s);
    }//GEN-LAST:event_okButtonActionPerformed
    
    public void printLine(String lineToPrint){
        System.out.println(lineToPrint);
        opWindow.append(lineToPrint+"\n");
        
    }
    /** 
     * Recursive function to extract the rule details in array format.
     * @param ruleName - the prefix for the rule being processed.
     * @param rR
     * @return re
     */
    private ArrayList<String> getRules(String ruleName,ruleRep rR){
        ArrayList<String> temp = new ArrayList<>();
        for(String s:(ArrayList<String>)rR.getCharList()){            
            if(s.contains("R")) // if this symbol contains a Rule...
                temp.addAll(getRules(ruleName+"-"+globalRules.get(s).getName(), globalRules.get(s)));
            else
                temp.add(ruleName+"-"+s);
        }
        return temp;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sequiturSortGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sequiturSortGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sequiturSortGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sequiturSortGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sequiturSortGUI().setVisible(true);
            }
        });
    }
    
    /**
     * A Class for each "Rule Representation" in the Sequitur output window.
     * <br/><i>Basically this represents a row</i>
     */
    public class ruleRep{        
        private boolean complete = false;
        private String name = "";
        ArrayList<String> charList;
        ArrayList<String> ruleList;
        Integer ruleTime = 0;
        /**
         * Constructor - requires a string that represents the rule.
         * @param lineEntry 
         */
        public ruleRep(String lineEntry){
            charList = new ArrayList<>();            
            String rule, tempString;
            rule = lineEntry.substring(lineEntry.indexOf("R")-1).trim();
            name = rule.substring(0, rule.indexOf("->")-1).trim();
            tempString = rule.substring(rule.indexOf("->")+2);
            tempString = tempString.substring(0, tempString.length()-1).trim();
            tempString = tempString.replaceAll("\\W*,\\W*", ",");
            //charList.addAll(Arrays.asList(lineEntry.substring(lineEntry.indexOf("->")).split(","))); //<<<<< Updated via netbeans reccommendations.                        
            charList.addAll(Arrays.asList(tempString.split(","))); //<<<<< Updated via netbeans reccommendations.                        
            ruleList = (ArrayList)charList.clone();
        }
        
        /** Return an ArrayList representing the symbols in this rule **/
        public ArrayList getCharList(){ return ruleList; }
        /** Function to access the name of the rule **/
        public String getName(){ return this.name;}
        
        /** Function to check if the rule processing is complete **/
        public boolean isComplete(){return complete;}
        
        /**
         * Function for which replaces the segment names with the times.
         * 
         * @param segmentTimes a hashmap containing &lt;SegmentName,segmentTime&gt;
         * @return TRUE if the segment is complete - FALSE if not.
         */
        public Map sortRuleRep(Map segmentTimes){
            complete = true; // start by assuming all items are on the list.
            for(int i=0; i<charList.size(); i++){
                if(segmentTimes.containsKey(charList.get(i))){ // check if this is on the list.
                    ruleTime += (Integer)segmentTimes.get(charList.get(i)); // increase the time for this rule
                    charList.remove(i--); // remove this from the list.                                        
                }
                else
                    complete = false;
            }        
            if(complete)
                segmentTimes.put(name, ruleTime);
            return segmentTimes;
        }
        
        public boolean checkKnownSegments(Map segmentTimes){
            if(charList == null|charList.size()==0) // if the charList has not been initialised
                return complete; // then we can't check known segments.
            for(String s:charList){ // otherwise, go though each symbol(character) in the rule
                if(!(s.startsWith("R")|segmentTimes.containsKey(s))) // if it isn't a rule but doesn't exist on the list
                    return false;   // then this is an invalid setup.
            }
            return true; // otherwise, we're all good.
        }
        
        /** Return the String results of the Sorting **/
        public String getRuleSortDetails(){return this.name+","+String.valueOf(this.ruleTime)+","+String.valueOf(complete);}
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbRules;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton okButton;
    private javax.swing.JTextArea opWindow;
    private javax.swing.JTextArea taSegments;
    private javax.swing.JTextArea taSequitur;
    // End of variables declaration//GEN-END:variables
}

